
    (function(){
      // Sample videos (local files generated by generate_videos.sh)
      const videos = [
        {id:1,title:'Big Buck Bunny',src:'videos/video1.mp4',poster:''},
        {id:2,title:'Elephants Dream',src:'videos/video2.mp4',poster:''},
        {id:3,title:'For Bigger Blazes',src:'videos/video3.mp4',poster:''},
        {id:4,title:'Sintel Trailer',src:'videos/video4.mp4',poster:''},
        {id:5,title:'Tears of Steel',src:'videos/video5.mp4',poster:''},
        {id:6,title:'For Bigger Escape',src:'videos/video6.mp4',poster:''},
        {id:7,title:'Subaru Outback',src:'videos/video7.mp4',poster:''},
        {id:8,title:'Volkswagen GTI Review',src:'videos/video8.mp4',poster:''}
      ]

      const STORAGE_KEY = 'yutoob_stats'
      let stats = {}
      try{ stats = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') }catch(e){ stats = {} }

      function saveStats(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(stats)) }

      function recommend(list){
        return list.slice().map(v=>{
          const s = stats[v.id] || {watchTime:0,liked:false}
          const score = (s.watchTime||0) + (s.liked?600:0)
          return Object.assign({},v,{score})
        }).sort((a,b)=>b.score-a.score)
      }

      // DOM helpers
      const $ = sel => document.querySelector(sel)
      const $$ = sel => Array.from(document.querySelectorAll(sel))

      let searchTerm = ''
      let currentPage = 'home'
      let currentGame = 'beat-tiles'
      let beatAnimationId = null
      let racerAnimationId = null
      let obbyAnimationId = null
      let tycoonIntervalId = null
      let lastRenderPage = null
      let beatAudio = null

      const beatSongs = [
        { id:'pulsar', title:'Pulsar Beat', artist:'Future City', src:'https://assets.mixkit.co/music/preview/mixkit-electro-future-ambient-541.mp3' },
        { id:'neon-drive', title:'Neon Drive', artist:'Skyline Pulse', src:'https://assets.mixkit.co/music/preview/mixkit-futuristic-electronic-1160.mp3' },
        { id:'hypercore', title:'Hypercore', artist:'Pulse Grid', src:'https://assets.mixkit.co/music/preview/mixkit-futuristic-technology-563.mp3' }
      ]

      const beatDifficulties = {
        easy: { label:'Easy', speed: 170, span: 1100, tileDensity: 1 },
        normal: { label:'Normal', speed: 220, span: 900, tileDensity: 1.25 },
        hard: { label:'Hard', speed: 280, span: 720, tileDensity: 1.5 }
      }

      const gameState = {
        beat: {
          score: 0,
          combo: 0,
          accuracy: 'Ready',
          tiles: [],
          lastSpawn: 0,
          speed: 220,
          spawnInterval: 900,
          running: false,
          selectedSong: 'pulsar',
          difficulty: 'normal'
        },
        tycoon: {
          cash: 90,
          income: 1.4,
          level: 1,
          multiplier: 1,
          upgrades: 0,
          lastTick: Date.now()
        },
        obby: {
          position: 1,
          score: 0,
          alive: true,
          obstacles: [],
          lastTime: 0,
          spawnCounter: 0,
          speed: 240,
          boost: 0,
          cooldown: 0
        },
        spaceRacer: {
          position: 1,
          score: 0,
          speed: 220,
          obstacles: [],
          lastTime: 0,
          spawnTimer: 0,
          boost: 0,
          cooldown: 0,
          distance: 0
        },
        puzzleGrid: {
          tiles: [],
          firstPick: null,
          secondPick: null,
          moves: 0,
          matches: 0,
          locked: false
        }
      }

      const webResults = [
        {title:'Yutoob Search Engine', url:'#', description:'A warm search experience that integrates Yutoob video discovery.'},
        {title:'Yutoob Videos', url:'#', description:'Find local Yutoob videos, watch them instantly, and get personalized recommendations.'},
        {title:'Yutoob Browser', url:'#', description:'A search browser home page with an integrated video playground.'}
      ]

      function executeSearch(){
        currentPage = 'results'
        render()
      }

      function render(){
        const root = document.getElementById('app')
        root.innerHTML = ''

        const topbar = document.createElement('header')
        topbar.className='topbar'
        topbar.innerHTML = `<a class="skip" href="#main-content">Skip to content</a><div class="logo">Yutoob Search</div><div class="search-row"><input class="search" placeholder="Search the web" aria-label="Search the web"></div><button class="btn-primary" id="search-button">Search</button>`

        const layout = document.createElement('div'); layout.className='layout'
        const sidebar = document.createElement('aside'); sidebar.className='sidebar'; sidebar.setAttribute('role','navigation')
        sidebar.innerHTML = `
          <button class="side-item ${currentPage === 'home' ? 'active' : ''}" data-page="home">Home</button>
          <button class="side-item ${currentPage === 'results' ? 'active' : ''}" data-page="results">Search</button>
          <button class="side-item ${currentPage === 'games' ? 'active' : ''}" data-page="games">Games</button>
          <button class="side-item ${currentPage === 'about' ? 'active' : ''}" data-page="about">About</button>
        `
        const main = document.createElement('main'); main.className='main'; main.id='main-content'; main.setAttribute('role','main');

        const hero = document.createElement('section'); hero.className='hero'
        if(currentPage === 'home'){
          hero.innerHTML = `<div><h1>Search the web with Yutoob</h1><p>Video search, local playback, and a friendly browsing experience all in one place.</p></div><div class="hero-search"><input class="hero-input" type="search" placeholder="Search anything" value="${searchTerm}" aria-label="Search" /><button class="btn-primary" id="hero-search">Search</button></div>`
          main.appendChild(hero)
          const prompt = document.createElement('div')
          prompt.className = 'hero-sub'
          prompt.innerHTML = '<p>Use the search bar above to find Yutoob results and Yutoob videos.</p>'
          main.appendChild(prompt)
          const adCard = document.createElement('section')
          adCard.className = 'game-ad-card'
          adCard.innerHTML = `<div><span class="ad-chip">Game Hub</span><h2>Play the new Yutoob Game Hub</h2><p>Try Beat Tiles, Cyber Tycoon, Space Racer, Neon Obby, or Puzzle Grid right now. Press the button to jump straight into the arcade.</p></div><div class="game-ad-image"></div><button class="btn-primary" id="game-ad-open">Open Games</button>`
          main.appendChild(adCard)
        } else if(currentPage === 'games'){
          hero.innerHTML = `<div><h1>Future arcade in a click</h1><p>Choose a futuristic minigame and play Beat Tiles, Space Racer, Cyber Tycoon, Neon Obby, or Puzzle Grid.</p></div>`
          main.appendChild(hero)
        } else if(currentPage === 'about'){
          hero.innerHTML = `<div><h1>About Yutoob</h1><p>The future of video discovery, local playback and new game modes in one glowing experience.</p></div>`
          main.appendChild(hero)
          const prompt = document.createElement('div')
          prompt.className = 'hero-sub'
          prompt.innerHTML = '<p>Try the new Games tab for rhythm, tycoon, and obstacle course action.</p>'
          main.appendChild(prompt)
        } else {
          hero.innerHTML = `<div><h1>Search results for "${searchTerm}"</h1><p>Showing web results and Yutoob video recommendations.</p></div>`
          main.appendChild(hero)
        }

        if(currentPage === 'results'){
          const resultsSection = document.createElement('section'); resultsSection.className = 'results-section'
          const webList = document.createElement('div'); webList.className='web-results'
          webResults.forEach(item => {
            const card = document.createElement('div'); card.className='web-card'
            card.innerHTML = `<a class="web-title" href="${item.url}">${item.title}</a><p class="web-description">${item.description}</p>`
            webList.appendChild(card)
          })
          resultsSection.appendChild(webList)

          const videoHeading = document.createElement('div'); videoHeading.className='video-heading'; videoHeading.innerHTML = '<h2>Yutoob video results</h2>'
          main.appendChild(resultsSection)
          main.appendChild(videoHeading)

          const grid = document.createElement('div'); grid.className='grid'
          const list = recommend(videos).filter(v => v.title.toLowerCase().includes(searchTerm.toLowerCase()))
          list.forEach(v=>{
            const s = stats[v.id] || {watchTime:0,liked:false}
            const watched = Math.floor((s.watchTime||0)/60)
            const badgeText = s.liked ? '♥' : (s.watchTime > 120 ? '🔥' : (watched ? watched + 'm' : 'New'))
            const card = document.createElement('div'); card.className='video-card'
            card.tabIndex = 0
            card.setAttribute('role','button')
            card.setAttribute('aria-label', `Open video ${v.title}`)
            const poster = v.poster || 'https://via.placeholder.com/320x180?text=Video'
            card.innerHTML = `<div class="thumb"><img src="${poster}" alt="${v.title}"><div class="score-badge">${badgeText}</div><button class="like-btn" aria-label="${s.liked ? 'Unlike' : 'Like'}">${s.liked ? '♥' : '♡'}</button></div><div class="meta"><div class="title">${v.title}</div><div class="channel">Yutoob Channel • ${watched} min</div></div>`
            card.addEventListener('click',()=>openPlayer(v))
            card.addEventListener('keydown',e=>{ if(e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openPlayer(v) } })
            const likeBtn = card.querySelector('.like-btn')
            likeBtn.addEventListener('click',e=>{ e.stopPropagation(); toggleLike(v.id); likeBtn.setAttribute('aria-label', (stats[v.id] && stats[v.id].liked) ? 'Unlike' : 'Like') })
            grid.appendChild(card)
          })
          main.appendChild(grid)
        }

        if(currentPage === 'games'){
          main.appendChild(renderGames())
        }

        layout.appendChild(sidebar)
        layout.appendChild(main)
        root.appendChild(topbar)
        root.appendChild(layout)

        const searchEl = topbar.querySelector('.search')
        const heroInput = main.querySelector('.hero-input')
        const searchButton = topbar.querySelector('#search-button')
        const heroButton = main.querySelector('#hero-search')

        function attachSearch(el){
          if(!el) return
          el.value = searchTerm
          el.addEventListener('input', e => { searchTerm = e.target.value })
          el.addEventListener('keydown', e => { if(e.key === 'Enter'){ executeSearch() } })
        }
        attachSearch(searchEl)
        attachSearch(heroInput)

        if(searchButton) searchButton.addEventListener('click', executeSearch)
        if(heroButton) heroButton.addEventListener('click', executeSearch)
        const gameAdButton = document.getElementById('game-ad-open')
        if(gameAdButton){
          gameAdButton.addEventListener('click', () => {
            currentPage = 'games'
            currentGame = 'beat-tiles'
            stopAllGameLoops()
            render()
          })
        }

        sidebar.querySelectorAll('[data-page]').forEach(btn => {
          btn.addEventListener('click', () => {
            const page = btn.getAttribute('data-page')
            if(page === 'games' && currentPage !== 'games'){
              currentPage = 'games'
              currentGame = 'beat-tiles'
            } else if(page !== currentPage){
              currentPage = page
            }
            stopAllGameLoops()
            render()
          })
        })

        renderDebug()
      }

      // Player
      let current = null
      let playStart = null

      function openPlayer(v){
        current = v
        const modal = document.createElement('div'); modal.className='modal'
        modal.tabIndex = -1
        modal.setAttribute('role','dialog')
        modal.setAttribute('aria-modal','true')
        const player = document.createElement('div'); player.className='player'
        player.innerHTML = `<video controls autoplay src="${v.src}" poster="${v.poster||''}"></video><div class="player-title">${v.title}</div><div style="padding:0 12px 12px"><button id="player-like" class="btn" aria-label="${(stats[v.id]&&stats[v.id].liked)?'Unlike':'Like'}">${(stats[v.id]&&stats[v.id].liked)?'Unlike':'Like'}</button></div>`
        modal.appendChild(player)
        modal.addEventListener('click',closePlayer)
        player.addEventListener('click',e=>e.stopPropagation())
        document.body.appendChild(modal)
        modal.focus()

        const videoEl = player.querySelector('video')
        videoEl.setAttribute('aria-label', v.title)
        videoEl.addEventListener('play',()=>{
          playStart = Date.now()
        })
        function addDelta(){
          if(!playStart) return
          const delta = Math.floor((Date.now()-playStart)/1000)
          playStart = null
          stats[v.id] = stats[v.id] || {watchTime:0,liked:false}
          stats[v.id].watchTime = (stats[v.id].watchTime||0) + delta
          saveStats()
          render()
        }
        videoEl.addEventListener('pause', addDelta)
        videoEl.addEventListener('ended', addDelta)

        const likeBtn = player.querySelector('#player-like')
        likeBtn.addEventListener('click',()=>{ toggleLike(v.id); likeBtn.textContent = (stats[v.id]&&stats[v.id].liked)?'Unlike':'Like' })

        modal.addEventListener('keydown', e => { if(e.key === 'Escape') closePlayer() })
      }

      function closePlayer(){
        // if video playing, add delta
        if(playStart && current){
          const delta = Math.floor((Date.now()-playStart)/1000)
          stats[current.id] = stats[current.id] || {watchTime:0,liked:false}
          stats[current.id].watchTime = (stats[current.id].watchTime||0) + delta
          playStart = null
        }
        const modal = document.querySelector('.modal')
        if(modal) modal.remove()
        current = null
        saveStats()
        render()
      }

      function toggleLike(id){
        stats[id] = stats[id] || {watchTime:0,liked:false}
        stats[id].liked = !stats[id].liked
        saveStats()
        render()
      }

      function stopAllGameLoops(){
        if(beatAnimationId){ cancelAnimationFrame(beatAnimationId); beatAnimationId = null }
        if(racerAnimationId){ cancelAnimationFrame(racerAnimationId); racerAnimationId = null }
        if(obbyAnimationId){ cancelAnimationFrame(obbyAnimationId); obbyAnimationId = null }
        if(tycoonIntervalId){ clearInterval(tycoonIntervalId); tycoonIntervalId = null }
        document.removeEventListener('keydown', handleBeatKeydown)
        document.removeEventListener('keydown', handleRacerKeydown)
        document.removeEventListener('keydown', handleObbyKeydown)
        if(beatAudio){ beatAudio.pause(); beatAudio = null }
      }

      function renderGames(){
        const gamesRoot = document.createElement('div')
        const title = document.createElement('section'); title.className='hero'
        title.innerHTML = `<div><h1>Play in neon mode</h1><p>Jump into a futuristic game hub with rhythm, tycoon, and obby challenges.</p></div>`
        gamesRoot.appendChild(title)

        const modeRow = document.createElement('div'); modeRow.className='game-mode-row'
        const modes = [
          { id:'beat-tiles', title:'Beat Tiles', description:'Tap the neon track when falling tiles hit the center zone for perfect+ timing.', icon:'🎵' },
          { id:'tycoon', title:'Cyber Tycoon', description:'Build a glowing business, buy upgrades, and watch the credits flow.', icon:'💎' },
          { id:'space-racer', title:'Space Racer', description:'Race through neon lanes, avoid cosmic obstacles and keep your ship alive.', icon:'🚀' },
          { id:'obby', title:'Neon Obby', description:'Dodge hazards in a bright runner course and survive as long as you can.', icon:'🏃' },
          { id:'puzzle-grid', title:'Puzzle Grid', description:'Match the glowing tiles in a futuristic board puzzle mission.', icon:'🧩' }
        ]
        modes.forEach(mode => {
          const card = document.createElement('button')
          card.type = 'button'
          card.className = 'game-card-mini' + (currentGame === mode.id ? ' active' : '')
          card.innerHTML = `<div class="card-icon">${mode.icon}</div><h3>${mode.title}</h3><p>${mode.description}</p>`
          card.addEventListener('click', () => {
            currentGame = mode.id
            stopAllGameLoops()
            render()
          })
          modeRow.appendChild(card)
        })
        gamesRoot.appendChild(modeRow)

        const panel = document.createElement('div'); panel.className = 'game-panel'
        if(currentGame === 'beat-tiles'){
          renderBeatTiles(panel)
        } else if(currentGame === 'tycoon'){
          renderTycoonPanel(panel)
        } else if(currentGame === 'space-racer'){
          renderRacerPanel(panel)
        } else if(currentGame === 'obby'){
          renderObbyPanel(panel)
        } else if(currentGame === 'puzzle-grid'){
          renderPuzzlePanel(panel)
        }
        gamesRoot.appendChild(panel)
        return gamesRoot
      }

      function renderBeatTiles(container){
        const state = gameState.beat
        const song = beatSongs.find(s => s.id === state.selectedSong) || beatSongs[0]
        const difficulty = beatDifficulties[state.difficulty]

        const header = document.createElement('div'); header.className = 'game-info'
        header.innerHTML = `<div class="game-score-card"><strong>Beat Tiles</strong><span>${state.score} pts</span><p>Now playing: ${song.title} — ${song.artist}</p></div>`
        container.appendChild(header)

        const controls = document.createElement('div'); controls.className='game-actions'
        const songLabel = document.createElement('div'); songLabel.style.flex='1'
        songLabel.innerHTML = `<strong style="display:block;margin-bottom:6px;color:#fff">Song</strong>`
        const songSelect = document.createElement('select')
        songSelect.style.width='100%'
        beatSongs.forEach(s => {
          const option = document.createElement('option')
          option.value = s.id
          option.textContent = `${s.title} — ${s.artist}`
          if(s.id === state.selectedSong) option.selected = true
          songSelect.appendChild(option)
        })
        songSelect.addEventListener('change', () => {
          state.selectedSong = songSelect.value
          updateBeatAudio()
          render()
        })
        songLabel.appendChild(songSelect)
        controls.appendChild(songLabel)

        const difficultySelector = document.createElement('div'); difficultySelector.style.display='flex'; difficultySelector.style.gap='10px'; difficultySelector.style.flex='1';
        Object.keys(beatDifficulties).forEach(key => {
          const diff = beatDifficulties[key]
          const btn = document.createElement('button'); btn.className='btn' + (state.difficulty === key ? ' active' : ''); btn.textContent = diff.label
          btn.addEventListener('click', () => {
            state.difficulty = key
            state.speed = diff.speed
            state.spawnInterval = diff.span
            render()
          })
          difficultySelector.appendChild(btn)
        })
        controls.appendChild(difficultySelector)
        container.appendChild(controls)

        const board = document.createElement('div'); board.className = 'game-board'
        const canvas = document.createElement('canvas'); canvas.id = 'beat-canvas'; canvas.width = 760; canvas.height = 520
        board.appendChild(canvas)
        container.appendChild(board)

        if(beatAudio){ beatAudio.pause(); beatAudio = null }
        const audioPlayer = document.createElement('audio'); audioPlayer.id='beat-audio'; audioPlayer.style.width='100%'; audioPlayer.controls = true; audioPlayer.autoplay = true; audioPlayer.loop = true; audioPlayer.src = song.src
        container.appendChild(audioPlayer)
        beatAudio = audioPlayer

        const actions = document.createElement('div'); actions.className = 'game-actions'
        const hotkeys = ['D','F','J','K']
        hotkeys.forEach((key, idx) => {
          const btn = document.createElement('button'); btn.className = 'btn'; btn.textContent = `Tap ${key}`
          btn.addEventListener('click', () => hitBeatTile(idx))
          actions.appendChild(btn)
        })
        container.appendChild(actions)

        const tips = document.createElement('div'); tips.className = 'game-tips'
        tips.innerHTML = `<p><strong class="futuristic-text">Accuracy:</strong> ${state.accuracy} · <strong class="futuristic-text">Combo:</strong> ${state.combo} · <strong class="futuristic-text">Mode:</strong> ${difficulty.label}</p><p>Use D / F / J / K or tap the buttons. Harder songs and harder modes push the timing window tighter.</p>`
        container.appendChild(tips)

        if(!beatAnimationId){
          state.running = true
          state.lastTime = performance.now()
          state.lastSpawn = performance.now()
          state.speed = difficulty.speed
          state.spawnInterval = difficulty.span
          document.addEventListener('keydown', handleBeatKeydown)
          beatAnimationId = requestAnimationFrame(beatLoop)
        }
      }

      function updateBeatAudio(){
        const song = beatSongs.find(s => s.id === gameState.beat.selectedSong) || beatSongs[0]
        const audio = document.getElementById('beat-audio')
        if(audio){
          audio.src = song.src
          audio.play().catch(() => {})
        }
      }

      function handleBeatKeydown(event){
        const mapping = { d:0, f:1, j:2, k:3 }
        const key = event.key.toLowerCase()
        if(mapping[key] !== undefined){
          hitBeatTile(mapping[key])
        }
      }

      function hitBeatTile(lane){
        const state = gameState.beat
        const targetY = 460
        const candidates = state.tiles.filter(tile => tile.lane === lane)
        if(!candidates.length){ state.accuracy = 'Miss'; state.combo = 0; return }
        let best = null
        candidates.forEach(tile => {
          const diff = Math.abs((tile.y + 36) - targetY)
          if(!best || diff < best.diff){ best = { tile, diff } }
        })
        if(!best || best.diff > 90){ state.accuracy = 'Miss'; state.combo = 0; return }
        const dist = best.diff
        let score = 0
        let text = 'Good'
        if(dist < 12){ text = 'Perfect+'; score = 360 }
        else if(dist < 28){ text = 'Perfect'; score = 260 }
        else if(dist < 52){ text = 'Great'; score = 160 }
        else { text = 'Good'; score = 90 }
        state.score += score + state.combo * 4
        state.combo += 1
        state.accuracy = text
        state.tiles = state.tiles.filter(tile => tile !== best.tile)
      }

      function beatLoop(timestamp){
        const state = gameState.beat
        const difficulty = beatDifficulties[state.difficulty]
        const dt = (timestamp - state.lastTime) / 1000
        state.lastTime = timestamp
        if(timestamp - state.lastSpawn > state.spawnInterval){
          const count = Math.max(1, Math.round(difficulty.tileDensity))
          for(let i=0;i<count;i++){
            state.tiles.push({ lane: Math.floor(Math.random() * 4), y: -68 - i * 42, id: `tile-${Date.now()}-${Math.random()}` })
          }
          state.lastSpawn = timestamp
        }
        const speed = state.speed + state.score * 0.02
        state.tiles.forEach(tile => tile.y += speed * dt)
        state.tiles = state.tiles.filter(tile => {
          if(tile.y > 540){ state.accuracy = 'Miss'; state.combo = 0; return false }
          return true
        })
        drawBeatGame()
        if(currentPage === 'games' && currentGame === 'beat-tiles'){
          beatAnimationId = requestAnimationFrame(beatLoop)
        } else {
          beatAnimationId = null
        }
      }

      function drawBeatGame(){
        const canvas = document.getElementById('beat-canvas')
        if(!canvas) return
        const ctx = canvas.getContext('2d')
        ctx.clearRect(0,0,canvas.width,canvas.height)
        const grad = ctx.createLinearGradient(0,0,0,canvas.height)
        grad.addColorStop(0,'#1b0904'); grad.addColorStop(1,'#0c0502')
        ctx.fillStyle = grad
        ctx.fillRect(0,0,canvas.width,canvas.height)
        const laneWidth = 140
        const gap = 20
        const startX = 70
        for(let i=0;i<4;i++){
          const x = startX + i * (laneWidth + gap)
          ctx.fillStyle = 'rgba(255,142,64,0.12)'
          ctx.fillRect(x, 0, laneWidth, canvas.height)
          ctx.strokeStyle = 'rgba(255,142,64,0.18)'
          ctx.lineWidth = 2
          ctx.strokeRect(x, 0, laneWidth, canvas.height)
          ctx.fillStyle = 'rgba(255,142,64,0.06)'
          ctx.fillRect(x, 420, laneWidth, 110)
        }
        const targetY = 460
        ctx.strokeStyle = 'rgba(255,142,64,0.85)'
        ctx.lineWidth = 4
        ctx.beginPath(); ctx.moveTo(startX, targetY); ctx.lineTo(startX + 4*(laneWidth+gap) - gap, targetY); ctx.stroke()
        ctx.fillStyle = 'rgba(255,142,64,0.16)'
        ctx.fillRect(startX, targetY - 34, 4*(laneWidth+gap) - gap, 68)
        gameState.beat.tiles.forEach(tile => {
          const x = startX + tile.lane * (laneWidth + gap) + 10
          ctx.fillStyle = 'rgba(255,142,64,0.95)'
          ctx.shadowColor = 'rgba(255,142,64,0.45)'
          ctx.shadowBlur = 22
          ctx.fillRect(x, tile.y, laneWidth - 20, 48)
          ctx.shadowBlur = 0
        })
        ctx.fillStyle = '#fff1dc'
        ctx.font = '700 22px Inter'
        ctx.fillText(`Score: ${gameState.beat.score}`, 28, 42)
        ctx.fillText(`Combo: ${gameState.beat.combo}`, 28, 74)
        ctx.fillStyle = '#f4c99a'
        ctx.font = '600 18px Inter'
        ctx.fillText(`Hit: ${gameState.beat.accuracy}`, 28, 104)
      }

      function drawTycoonScene(){
        const canvas = document.getElementById('tycoon-canvas')
        if(!canvas) return
        const ctx = canvas.getContext('2d')
        const width = canvas.width
        const height = canvas.height
        ctx.clearRect(0,0,width,height)

        const bg = ctx.createLinearGradient(0,0,0,height)
        bg.addColorStop(0,'rgba(20,10,4,0.95)')
        bg.addColorStop(1,'rgba(10,4,2,0.9)')
        ctx.fillStyle = bg
        ctx.fillRect(0,0,width,height)

        const horizon = 120
        ctx.strokeStyle = 'rgba(255,142,64,0.18)'
        ctx.lineWidth = 2
        ctx.beginPath()
        ctx.moveTo(90,horizon)
        ctx.lineTo(width-90,horizon)
        ctx.stroke()

        ctx.fillStyle = 'rgba(255,142,64,0.06)'
        ctx.fillRect(80, horizon, width-160, height-horizon)

        const cube = (x,y,s,angle) => {
          ctx.save()
          ctx.translate(x,y)
          ctx.rotate(angle)
          ctx.fillStyle = 'rgba(255,178,120,0.95)'
          ctx.fillRect(-s/2, -s/2, s, s)
          ctx.fillStyle = 'rgba(255,142,64,0.75)'
          ctx.fillRect(-s/2, -s/2, s, s*0.4)
          ctx.restore()
        }

        cube(240,180,92,-0.12)
        cube(430,200,76,0.16)
        cube(550,150,110,-0.06)

        const glow = ctx.createRadialGradient(420, 140, 10, 420, 140, 110)
        glow.addColorStop(0,'rgba(255,196,141,0.55)')
        glow.addColorStop(1,'rgba(255,142,64,0)')
        ctx.fillStyle = glow
        ctx.fillRect(220, 40, 320, 220)

        ctx.fillStyle = '#fff1dc'
        ctx.font = '700 20px Inter'
        ctx.fillText('3D Arcade Vault', 32, 34)
        ctx.font = '500 14px Inter'
        ctx.fillStyle = '#f4c99a'
        ctx.fillText('Build your cyber business inside the hub.', 32, 58)
      }

      function renderTycoonPanel(container){
        const state = gameState.tycoon
        const header = document.createElement('div'); header.className = 'game-info'
        header.innerHTML = `<div class="game-score-card"><strong>Cyber Tycoon</strong><span>$${Math.floor(state.cash)}</span><p>Grow income, buy upgrades, and experience futuristic passive gains.</p></div>`
        container.appendChild(header)

        const scene = document.createElement('div'); scene.className = 'tycoon-scene'
        const canvas = document.createElement('canvas'); canvas.id = 'tycoon-canvas'; canvas.width = 760; canvas.height = 240
        scene.appendChild(canvas)
        container.appendChild(scene)
        drawTycoonScene()

        const stats = document.createElement('div'); stats.className = 'game-score-card'
        stats.innerHTML = `<strong>Income / second</strong><span>$${state.income.toFixed(1)}</span><p>Level ${state.level} · Multiplier x${state.multiplier.toFixed(1)}</p>`
        container.appendChild(stats)

        const actions = document.createElement('div'); actions.className = 'game-actions'
        const buttons = [
          { label: 'Collect Boost', action: () => { state.cash += 18; render() } },
          { label: `Buy Upgrade ($${40 + state.upgrades * 30})`, action: () => {
            const cost = 40 + state.upgrades * 30
            if(state.cash >= cost){ state.cash -= cost; state.income += 1.4 * state.multiplier; state.upgrades += 1; state.level += 1; render() }
          } },
          { label: `Launch Neon Vault ($${110 + state.upgrades * 25})`, action: () => {
            const cost = 110 + state.upgrades * 25
            if(state.cash >= cost){ state.cash -= cost; state.multiplier += 0.3; state.income += 2; render() }
          } },
          { label: `Sell Cyber Ads ($${20 + state.level * 10})`, action: () => {
            const earn = 20 + state.level * 10
            state.cash += earn
            state.income += 0.15
            render()
          } }
        ]
        buttons.forEach(btn => {
          const node = document.createElement('button'); node.className='btn'; node.textContent = btn.label
          node.addEventListener('click', btn.action)
          actions.appendChild(node)
        })
        container.appendChild(actions)
        const tips = document.createElement('div'); tips.className='game-tips'
        tips.innerHTML = '<p>Every second your business earns credits automatically. Use boosts, vault launches, and ad sales to stay ahead of the curve.</p>'
        container.appendChild(tips)
        if(!tycoonIntervalId){ startTycoonMode() }
      }

      function startTycoonMode(){
        if(tycoonIntervalId) return
        tycoonIntervalId = setInterval(() => {
          const state = gameState.tycoon
          state.cash += state.income
          if(currentPage === 'games' && currentGame === 'tycoon'){
            render()
          }
        }, 1000)
      }

      function renderObbyPanel(container){
        const state = gameState.obby
        const header = document.createElement('div'); header.className = 'game-info'
        header.innerHTML = `<div class="game-score-card"><strong>Neon Obby</strong><span>${state.score}m</span><p>Use ← / → or click the lanes to avoid glowing hazards.</p></div>`
        container.appendChild(header)

        const board = document.createElement('div'); board.className='game-board obby-perspective'
        const canvas = document.createElement('canvas'); canvas.id='obby-canvas'; canvas.width = 760; canvas.height = 420
        board.appendChild(canvas)
        container.appendChild(board)

        const actions = document.createElement('div'); actions.className='game-actions'
        const leftBtn = document.createElement('button'); leftBtn.className='btn'; leftBtn.textContent='Left'; leftBtn.addEventListener('click', () => moveObby(-1))
        const rightBtn = document.createElement('button'); rightBtn.className='btn'; rightBtn.textContent='Right'; rightBtn.addEventListener('click', () => moveObby(1))
        const boostBtn = document.createElement('button'); boostBtn.className='btn'; boostBtn.textContent='Boost'; boostBtn.addEventListener('click', activateObbyBoost)
        const restartBtn = document.createElement('button'); restartBtn.className='btn'; restartBtn.textContent='Restart'; restartBtn.addEventListener('click', resetObby)
        actions.append(leftBtn, rightBtn, boostBtn, restartBtn)
        container.appendChild(actions)

        const tips = document.createElement('div'); tips.className='game-tips'
        tips.innerHTML = `<p>Keep moving to the open lane and time your dodges. Survive longer to reach higher scores.</p><p>Boost slows the course for a short time and recharges quickly.</p>`
        container.appendChild(tips)

        if(!obbyAnimationId){
          state.lastTime = performance.now()
          state.alive = true
          document.addEventListener('keydown', handleObbyKeydown)
          obbyAnimationId = requestAnimationFrame(obbyLoop)
        }
      }

      function initPuzzleGrid(){
        const state = gameState.puzzleGrid
        const values = ['★','▲','●','■','◆','☀','⟁','✦']
        state.tiles = [...values, ...values].sort(() => Math.random() - 0.5).map((value, index) => ({
          id: `tile-${index}`,
          value,
          revealed: false,
          matched: false
        }))
        state.firstPick = null
        state.secondPick = null
        state.moves = 0
        state.matches = 0
        state.locked = false
      }

      function renderPuzzlePanel(container){
        const state = gameState.puzzleGrid
        if(!state.tiles.length){
          initPuzzleGrid()
        }

        const header = document.createElement('div'); header.className = 'game-info'
        header.innerHTML = `<div class="game-score-card"><strong>Puzzle Grid</strong><span>${state.matches * 100}</span><p>Find matching neon tiles and clear the board.</p></div>`
        container.appendChild(header)

        const banner = document.createElement('div'); banner.className = 'game-banner'
        banner.style.backgroundImage = "url('https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=900&q=80')"
        banner.innerHTML = `<h3>Match glowing tiles</h3><p>Flip tiles and pair the icons before the board fills.</p>`
        container.appendChild(banner)

        const grid = document.createElement('div'); grid.className = 'puzzle-grid'
        state.tiles.forEach((tile, index) => {
          const btn = document.createElement('button'); btn.type = 'button'
          btn.className = 'puzzle-tile' + (tile.revealed || tile.matched ? ' revealed' : '') + (tile.matched ? ' matched' : '')
          btn.textContent = tile.revealed || tile.matched ? tile.value : ''
          btn.addEventListener('click', () => handlePuzzlePick(index))
          grid.appendChild(btn)
        })
        container.appendChild(grid)

        const stats = document.createElement('div'); stats.className = 'game-stats'
        stats.innerHTML = `<div class="game-score-card"><strong>Moves</strong><span>${state.moves}</span></div><div class="game-score-card"><strong>Matches</strong><span>${state.matches}/8</span></div><div class="game-score-card"><strong>Status</strong><span>${state.matches === 8 ? 'Victory' : state.locked ? 'Waiting' : 'Ready'}</span></div>`
        container.appendChild(stats)

        const actions = document.createElement('div'); actions.className='game-actions'
        const resetBtn = document.createElement('button'); resetBtn.className='btn'; resetBtn.textContent='Shuffle'; resetBtn.addEventListener('click', () => { initPuzzleGrid(); render() })
        actions.appendChild(resetBtn)
        container.appendChild(actions)
      }

      function handlePuzzlePick(index){
        const state = gameState.puzzleGrid
        if(state.locked) return
        const tile = state.tiles[index]
        if(tile.revealed || tile.matched) return
        tile.revealed = true
        if(!state.firstPick){
          state.firstPick = tile
        } else if(!state.secondPick){
          state.secondPick = tile
          state.moves += 1
          if(state.firstPick.value === state.secondPick.value){
            state.firstPick.matched = true
            state.secondPick.matched = true
            state.matches += 1
            state.firstPick = null
            state.secondPick = null
          } else {
            state.locked = true
            setTimeout(() => {
              state.firstPick.revealed = false
              state.secondPick.revealed = false
              state.firstPick = null
              state.secondPick = null
              state.locked = false
              render()
            }, 700)
          }
        }
        render()
      }

      function renderRacerPanel(container){
        const state = gameState.spaceRacer
        const header = document.createElement('div'); header.className = 'game-info'
        header.innerHTML = `<div class="game-score-card"><strong>Space Racer</strong><span>${Math.floor(state.distance)}m</span><p>Control the ship and avoid the glowing asteroids.</p></div>`
        container.appendChild(header)

        const banner = document.createElement('div'); banner.className = 'game-banner'
        banner.style.backgroundImage = "url('https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=900&q=80')"
        banner.innerHTML = `<h3>Neon lane racing</h3><p>Use ← / → and boost to keep your ship ahead of the pulse wave.</p>`
        container.appendChild(banner)

        const board = document.createElement('div'); board.className='game-board'
        const canvas = document.createElement('canvas'); canvas.id='racer-canvas'; canvas.width = 760; canvas.height = 420
        board.appendChild(canvas)
        container.appendChild(board)

        const actions = document.createElement('div'); actions.className='game-actions'
        const leftBtn = document.createElement('button'); leftBtn.className='btn'; leftBtn.textContent='Left'; leftBtn.addEventListener('click', () => moveRacer(-1))
        const rightBtn = document.createElement('button'); rightBtn.className='btn'; rightBtn.textContent='Right'; rightBtn.addEventListener('click', () => moveRacer(1))
        const boostBtn = document.createElement('button'); boostBtn.className='btn'; boostBtn.textContent='Boost'; boostBtn.addEventListener('click', activateRacerBoost)
        const restartBtn = document.createElement('button'); restartBtn.className='btn'; restartBtn.textContent='Restart'; restartBtn.addEventListener('click', resetRacer)
        actions.append(leftBtn, rightBtn, boostBtn, restartBtn)
        container.appendChild(actions)

        const tips = document.createElement('div'); tips.className='game-tips'
        tips.innerHTML = '<p>Stay in the clear lane. Boost slows obstacles and increases your score.</p><p>Collect distance by surviving longer.</p>'
        container.appendChild(tips)

        if(!racerAnimationId){
          state.lastTime = performance.now()
          document.addEventListener('keydown', handleRacerKeydown)
          racerAnimationId = requestAnimationFrame(racerLoop)
        }
      }

      function moveRacer(direction){
        const state = gameState.spaceRacer
        state.position = Math.max(0, Math.min(2, state.position + direction))
      }

      function activateRacerBoost(){
        const state = gameState.spaceRacer
        if(state.cooldown > 0) return
        state.boost = 0.7
        state.cooldown = 4
      }

      function resetRacer(){
        gameState.spaceRacer = { position: 1, score: 0, speed: 220, obstacles: [], lastTime: performance.now(), spawnTimer: 0, boost: 0, cooldown: 0, distance: 0 }
        if(racerAnimationId){ cancelAnimationFrame(racerAnimationId); racerAnimationId = null }
        document.removeEventListener('keydown', handleRacerKeydown)
        render()
      }

      function handleRacerKeydown(event){
        if(event.key === 'ArrowLeft' || event.key.toLowerCase() === 'a'){ moveRacer(-1) }
        if(event.key === 'ArrowRight' || event.key.toLowerCase() === 'd'){ moveRacer(1) }
        if(event.key.toLowerCase() === 's' || event.key === ' '){ activateRacerBoost() }
      }

      function racerLoop(timestamp){
        const state = gameState.spaceRacer
        const dt = (timestamp - state.lastTime) / 1000
        state.lastTime = timestamp
        state.spawnTimer += dt
        if(state.spawnTimer > 0.95){
          state.obstacles.push({ lane: Math.floor(Math.random() * 3), y: -80, id: `obs-${Date.now()}-${Math.random()}` })
          state.spawnTimer = 0
        }
        const obstacleSpeed = state.speed * (state.boost > 0 ? 0.5 : 1) + Math.min(100, state.distance * 0.4)
        state.obstacles.forEach(obs => obs.y += obstacleSpeed * dt)
        state.obstacles = state.obstacles.filter(obs => obs.y < 460)
        if(state.boost > 0){ state.boost = Math.max(0, state.boost - dt) }
        if(state.cooldown > 0){ state.cooldown = Math.max(0, state.cooldown - dt) }
        state.distance += dt * (state.boost > 0 ? 14 : 10)
        state.obstacles.forEach(obs => {
          if(obs.lane === state.position && obs.y > 330 && obs.y < 380){ resetRacer() }
        })
        drawRacerScene()
        if(currentPage === 'games' && currentGame === 'space-racer'){
          racerAnimationId = requestAnimationFrame(racerLoop)
        } else {
          racerAnimationId = null
        }
      }

      function drawRacerScene(){
        const canvas = document.getElementById('racer-canvas')
        if(!canvas) return
        const ctx = canvas.getContext('2d')
        const width = canvas.width
        const height = canvas.height
        ctx.clearRect(0,0,width,height)
        ctx.fillStyle = '#0b0f1d'
        ctx.fillRect(0,0,width,height)
        const glow = ctx.createLinearGradient(0,0,width,0)
        glow.addColorStop(0,'rgba(255,142,64,0.12)')
        glow.addColorStop(0.5,'rgba(255,255,255,0.15)')
        glow.addColorStop(1,'rgba(255,142,64,0.12)')
        ctx.fillStyle = glow
        ctx.fillRect(0,120,width,200)
        const laneW = width / 3
        for(let i=1;i<3;i++){
          ctx.strokeStyle='rgba(255,142,64,0.14)'
          ctx.lineWidth=2
          ctx.beginPath()
          ctx.moveTo(i*laneW,120)
          ctx.lineTo(i*laneW,height-40)
          ctx.stroke()
        }
        ctx.fillStyle='rgba(255,142,64,0.08)'
        for(let i=0;i<5;i++){
          const y=120 + i*60
          ctx.fillRect(0,y,width,10)
        }
        const state = gameState.spaceRacer
        const shipX = state.position*laneW + laneW/2
        ctx.fillStyle='#ff8e40'
        ctx.beginPath()
        ctx.moveTo(shipX,360)
        ctx.lineTo(shipX-18,400)
        ctx.lineTo(shipX+18,400)
        ctx.closePath()
        ctx.fill()
        ctx.fillStyle='rgba(255,255,255,0.9)'
        ctx.beginPath()
        ctx.arc(shipX,352,10,0,Math.PI*2)
        ctx.fill()
        state.obstacles.forEach(obs => {
          ctx.fillStyle='rgba(255,80,61,0.92)'
          const x = obs.lane*laneW + laneW/2
          ctx.beginPath()
          ctx.moveTo(x,obs.y)
          ctx.lineTo(x-22,obs.y+40)
          ctx.lineTo(x+22,obs.y+40)
          ctx.closePath()
          ctx.fill()
        })
      }

      function handleObbyKeydown(event){
        if(event.key === 'ArrowLeft' || event.key.toLowerCase() === 'a'){ moveObby(-1) }
        if(event.key === 'ArrowRight' || event.key.toLowerCase() === 'd'){ moveObby(1) }
        if(event.key.toLowerCase() === 's' || event.key === ' '){ activateObbyBoost() }
      }

      function activateObbyBoost(){
        const state = gameState.obby
        if(state.cooldown > 0 || !state.alive) return
        state.boost = 0.7
        state.cooldown = 4
      }

      function moveObby(direction){
        const state = gameState.obby
        state.position = Math.max(0, Math.min(2, state.position + direction))
      }

      function resetObby(){
        gameState.obby = { position: 1, score: 0, alive: true, obstacles: [], lastTime: performance.now(), spawnCounter: 0 }
        if(obbyAnimationId){ cancelAnimationFrame(obbyAnimationId); obbyAnimationId=null }
        document.removeEventListener('keydown', handleObbyKeydown)
        render()
      }

      function obbyLoop(timestamp){
        const state = gameState.obby
        if(!state.alive){ drawObby(); obbyAnimationId = null; return }
        const dt = (timestamp - state.lastTime) / 1000
        state.lastTime = timestamp
        state.spawnCounter += dt * (state.score > 30 ? 1.2 : 1)
        if(state.spawnCounter > 1.1){
          state.obstacles.push({ lane: Math.floor(Math.random() * 3), y: -60, id: `obs-${Date.now()}-${Math.random()}` })
          state.spawnCounter = 0
        }
        const obstacleSpeed = state.speed * (state.boost > 0 ? 0.55 : 1) + Math.min(120, state.score * 0.6)
        state.obstacles.forEach(obs => obs.y += obstacleSpeed * dt)
        state.obstacles = state.obstacles.filter(obs => obs.y < 460)
        if(state.boost > 0){ state.boost -= dt; }
        if(state.cooldown > 0){ state.cooldown = Math.max(0, state.cooldown - dt) }
        const playerY = 340
        const playerLane = state.position
        state.obstacles.forEach(obs => {
          if(obs.lane === playerLane && obs.y > playerY - 24 && obs.y < playerY + 42){
            state.alive = false
          }
        })
        if(state.alive){ state.score += dt * (state.boost > 0 ? 9 : 6) }
        drawObby()
        if(state.alive && currentPage === 'games' && currentGame === 'obby'){
          obbyAnimationId = requestAnimationFrame(obbyLoop)
        } else {
          obbyAnimationId = null
        }
      }

      function drawObby(){
        const canvas = document.getElementById('obby-canvas')
        if(!canvas) return
        const ctx = canvas.getContext('2d')
        const width = canvas.width
        const height = canvas.height
        ctx.clearRect(0,0,width,height)
        ctx.fillStyle = '#140804'
        ctx.fillRect(0,0,width,height)
        const leftTop = 160
        const rightTop = width - 160
        const leftBottom = 60
        const rightBottom = width - 60
        const horizon = 90

        ctx.fillStyle = 'rgba(255,142,64,0.06)'
        ctx.beginPath()
        ctx.moveTo(leftTop, horizon)
        ctx.lineTo(rightTop, horizon)
        ctx.lineTo(rightBottom, height)
        ctx.lineTo(leftBottom, height)
        ctx.closePath()
        ctx.fill()

        for(let i=1;i<6;i++){
          const t = i / 6
          const xTop = leftTop + (rightTop - leftTop) * t
          const xBottom = leftBottom + (rightBottom - leftBottom) * t
          ctx.strokeStyle = 'rgba(255,142,64,0.12)'
          ctx.lineWidth = 1
          ctx.beginPath()
          ctx.moveTo(xTop, horizon)
          ctx.lineTo(xBottom, height)
          ctx.stroke()
        }

        const laneWidthTop = (rightTop - leftTop) / 3
        const laneWidthBottom = (rightBottom - leftBottom) / 3
        ctx.strokeStyle = 'rgba(255,142,64,0.18)'
        ctx.lineWidth = 2
        for(let i=1;i<3;i++){
          const xTop = leftTop + laneWidthTop * i
          const xBottom = leftBottom + laneWidthBottom * i
          ctx.beginPath()
          ctx.moveTo(xTop, horizon)
          ctx.lineTo(xBottom, height)
          ctx.stroke()
        }

        gameState.obby.obstacles.forEach(obs => {
          const progress = Math.min(1, Math.max(0, (obs.y + 60) / (height - horizon)))
          const xTop = leftTop + obs.lane * laneWidthTop
          const xBottom = leftBottom + obs.lane * laneWidthBottom
          const x = xTop + (xBottom - xTop) * progress + 8
          const w = 100 + progress * 60
          const y = horizon + (height - horizon) * progress - 20
          ctx.fillStyle = 'rgba(255,142,64,0.95)'
          ctx.shadowColor = 'rgba(255,142,64,0.35)'
          ctx.shadowBlur = 16
          ctx.fillRect(x, y, w, 28)
          ctx.shadowBlur = 0
        })

        const playerProgress = 0.78
        const playerX = leftTop + gameState.obby.position * laneWidthTop + (leftBottom + gameState.obby.position * laneWidthBottom - (leftTop + gameState.obby.position * laneWidthTop)) * playerProgress + 8
        const playerW = 120 + playerProgress * 60
        ctx.fillStyle = gameState.obby.alive ? 'rgba(255,196,141,0.95)' : 'rgba(255,102,56,0.95)'
        ctx.fillRect(playerX, 340, playerW, 44)

        ctx.fillStyle = '#fff1dc'
        ctx.font = '700 22px Inter'
        ctx.fillText(`Score: ${Math.floor(gameState.obby.score)}m`, 28, 38)
        ctx.font = '600 16px Inter'
        ctx.fillStyle = '#f4c99a'
        ctx.fillText(`Boost: ${gameState.obby.boost > 0 ? 'Active' : gameState.obby.cooldown > 0 ? Math.ceil(gameState.obby.cooldown)+'s' : 'Ready'}`, 28, 66)
        if(!gameState.obby.alive){
          ctx.fillStyle = 'rgba(0,0,0,0.65)'
          ctx.fillRect(120, 160, 520, 120)
          ctx.fillStyle = 'rgba(255,102,56,0.95)'
          ctx.font = '700 32px Inter'
          ctx.fillText('Game Over', 260, 215)
          ctx.font = '500 18px Inter'
          ctx.fillStyle = '#fff1dc'
          ctx.fillText('Press Restart to run again', 236, 255)
        }
      }

      // Debug view (optional)
      function renderDebug(){
        let dbg = document.querySelector('.stats-debug')
        if(!dbg){ dbg = document.createElement('div'); dbg.className='stats-debug'; document.body.appendChild(dbg) }
        dbg.innerHTML = '<strong>Stats (localStorage)</strong><br/>' + Object.keys(stats).map(k=>{
          const s = stats[k]; return `#${k}: ${s.watchTime || 0}s ${s.liked? '♥':' '}`
        }).join('<br/>')
      }

      // initial render
      render()

      // expose for console debugging
      window.__YUTOOB = { videos, stats, recommend }
    })()
    